name: test build

on:
  push:

jobs:
  build-plugin:
    name: build-plugin
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.FYLR_BOT_PERSONAL_ACCESS_TOKEN }}
          submodules: true

      - name: Install dependencies
        run: |
          apt-get install -y curl python2 rsync make git
          npm install -g coffeescript@1 sass

      - name: Build plugin
        run: make
